import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.body_container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header_container}>
				{/* Headers can come in different sizes, all the way from h1 to h6 */}
				<h1>Portfolio</h1>
			</header>

			<nav className={styles.nav_container}>
				<a className={styles.nav_links} href="#">
					{" "}
					Blog{" "}
				</a>
				<a className={styles.nav_links} href="#">
					{" "}
					About{" "}
				</a>
				<a className={styles.nav_links} href="#">
					{" "}
					Projects{" "}
				</a>
				<a
					className={styles.nav_links}
					href="https://github.com/dmrt209"
				>
					{" "}
					Github{" "}
				</a>
			</nav>

			<main className={styles.main_container}>
				<h1>Hello, I'm David!</h1>
				<pre className={styles.pre_code_container}>
					<p className={styles.code_container}>
						👋 I am currently pursuing a Bachelor's degree in
						Computer Science
					</p>
					<p className={styles.code_container}>
						💻 I'm a Computer Science major at California State
						University Stanislaus.
					</p>
					<p className={styles.code_container}>
						💼 I am an incoming Information Security Intern at Apple!
					</p>
					<p className={styles.code_container}>
						💬 Feel free to talk to me about anything that you are passionate about.
					</p>

					{/* Add the terminal division */}
					<div id={styles.input} className={styles.terminal}></div>
				</pre>
				<p>
					This website can serve you and your projects. This page is
					hosted directly from your GitHub repository. Just edit,
					push, and your changes are live!
				</p>
			</main>
		</div>
	);
}

